version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server=kafka:9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  order-service:
    build: ./order-service
    environment:
      - KAFKA_BROKER=kafka:9092
    ports:
      - "3001:3001"
    depends_on:
      kafka:
        condition: service_healthy

  payment-service:
    build: ./payment-service
    environment:
      - KAFKA_BROKER=kafka:9092
    ports:
      - "3003:3003"
    depends_on:
      kafka:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    environment:
      - KAFKA_BROKER=kafka:9092
    ports:
      - "3004:3004"
    depends_on:
      kafka:
        condition: service_healthy
